# Generated by Django 5.0.7 on 2024-08-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("home_page", models.URLField(null=True)),
                ("message", models.TextField()),
            ],
        ),
    ]
