# Generated by Django 5.0.7 on 2024-08-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dzen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="main_comment",
            field=models.IntegerField(null=True),
        ),
    ]
