# Generated by Django 5.0.7 on 2024-08-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dzen", "0002_comment_main_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="home_page",
            field=models.URLField(blank=True, null=True),
        ),
    ]
