# Generated by Django 5.0.7 on 2024-08-06 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dzen", "0003_alter_comment_home_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="main_comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="dzen.comment",
            ),
        ),
    ]
