# Generated by Django 5.0.7 on 2024-08-06 23:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dzen", "0004_remove_comment_main_comment_comment_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="parent",
            new_name="main_comment",
        ),
    ]
