# Generated by Django 5.0.7 on 2024-08-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dzen", "0005_rename_parent_comment_main_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
